// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlYDObbCxQB1hgBJCxwZqdW5stcTcDn1g',
    appId: '1:48671377662:web:745e5d031b4bd1a09ebdaf',
    messagingSenderId: '48671377662',
    projectId: 'kaos-chattie',
    authDomain: 'kaos-chattie.firebaseapp.com',
    storageBucket: 'kaos-chattie.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY2SOLb7eRQy_OIr5V9QFRKW_g8dvqEOo',
    appId: '1:48671377662:android:06c6b79160e15aa39ebdaf',
    messagingSenderId: '48671377662',
    projectId: 'kaos-chattie',
    storageBucket: 'kaos-chattie.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6ysku_x8WvF0YNgRGEygdikewvSvKF4w',
    appId: '1:48671377662:ios:de658fe1e59aa3fd9ebdaf',
    messagingSenderId: '48671377662',
    projectId: 'kaos-chattie',
    storageBucket: 'kaos-chattie.appspot.com',
    iosClientId: '48671377662-7i8d85h2ma33ef3lfsq4bljjf212gona.apps.googleusercontent.com',
    iosBundleId: 'dev.kaos.chattie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6ysku_x8WvF0YNgRGEygdikewvSvKF4w',
    appId: '1:48671377662:ios:de658fe1e59aa3fd9ebdaf',
    messagingSenderId: '48671377662',
    projectId: 'kaos-chattie',
    storageBucket: 'kaos-chattie.appspot.com',
    iosClientId: '48671377662-7i8d85h2ma33ef3lfsq4bljjf212gona.apps.googleusercontent.com',
    iosBundleId: 'dev.kaos.chattie',
  );
}
