// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPebNeSFfIXhFHUfd7rjdevPKcqw8okKA',
    appId: '1:145279154636:web:9edfe4c1cd7f4b7456c569',
    messagingSenderId: '145279154636',
    projectId: 'kaosmpd-chattie',
    authDomain: 'kaosmpd-chattie.firebaseapp.com',
    databaseURL: 'https://kaosmpd-chattie-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kaosmpd-chattie.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF-jl4k9SqV1J9Ti9c6ENRKYZ8JABvz6E',
    appId: '1:145279154636:android:d602368eee990ad456c569',
    messagingSenderId: '145279154636',
    projectId: 'kaosmpd-chattie',
    databaseURL: 'https://kaosmpd-chattie-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kaosmpd-chattie.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2zSZh-ns3e_qXujrsfnisQgTh6ofcW14',
    appId: '1:145279154636:ios:8c7546be0f4b8b0d56c569',
    messagingSenderId: '145279154636',
    projectId: 'kaosmpd-chattie',
    databaseURL: 'https://kaosmpd-chattie-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kaosmpd-chattie.appspot.com',
    iosClientId: '145279154636-r8eheogtg1eojlchk3lqv07itgi3g7aq.apps.googleusercontent.com',
    iosBundleId: 'dev.kaos.chattie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2zSZh-ns3e_qXujrsfnisQgTh6ofcW14',
    appId: '1:145279154636:ios:8c7546be0f4b8b0d56c569',
    messagingSenderId: '145279154636',
    projectId: 'kaosmpd-chattie',
    databaseURL: 'https://kaosmpd-chattie-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kaosmpd-chattie.appspot.com',
    iosClientId: '145279154636-r8eheogtg1eojlchk3lqv07itgi3g7aq.apps.googleusercontent.com',
    iosBundleId: 'dev.kaos.chattie',
  );
}
